###
#   File name : Wenjun_Data_Preprocess.R
#   Author    : Hyunjin Kim
#   Date      : Feb 3, 2021
#   Email     : hyunjin.kim@stjude.org
#   Purpose   : Aggregate Cell Ranger output and preprocess the data
#   
#   Instruction
#               1. Source("Wenjun_Data_Preprocess.R")
#               2. Run the function "wenjun_preprocess" - specify the input path and the output directory
#               3. The results will be generated under the output directory
#
#   Example
#               > source("The_directory_of_Wenjun_Data_Preprocess.R/Wenjun_Data_Preprocess.R")
#               > wenjun_preprocess(callranger_result_dir="Z:/ResearchHome/SharedResources/Immunoinformatics/hkim8/Wenjun/Result/",
#                                   aggr_feature_bc_mat_dir="Z:/ResearchHome/SharedResources/Immunoinformatics/hkim8/Wenjun/Result/Wenjun_aggr/filtered_feature_bc_matrix/",
#                                   output_obj_path="./data/Wenjun_Seurat_Obj.RDS"
###

wenjun_preprocess <- function(callranger_result_dir="Z:/ResearchHome/SharedResources/Immunoinformatics/hkim8/Wenjun/Result/",
                              aggr_feature_bc_mat_dir="Z:/ResearchHome/SharedResources/Immunoinformatics/hkim8/Wenjun/Result/Wenjun_aggr/filtered_feature_bc_matrix/",
                              output_obj_path="./data/Wenjun_Seurat_Obj.RDS") {
  
  ### load libraries
  if(!require(dplyr, quietly = TRUE)) {
    install.packages("dplyr")
    require(dplyr, quietly = TRUE)
  }
  if(!require(Seurat, quietly = TRUE)) {
    install.packages("Seurat")
    require(Seurat, quietly = TRUE)
  }
  if(!require(patchwork, quietly = TRUE)) {
    install.packages("patchwork")
    require(patchwork, quietly = TRUE)
  }
  if(!require(ggplot2, quietly = TRUE)) {
    install.packages("ggplot2")
    require(ggplot2, quietly = TRUE)
  }
  if(!require(grid, quietly = TRUE)) {
    install.packages("grid")
    require(grid, quietly = TRUE)
  }
  if(!require(gridExtra, quietly = TRUE)) {
    install.packages("gridExtra")
    require(gridExtra, quietly = TRUE)
  }
  
  
  ### get separate folders in the cell ranger out dir
  sample_folders <- list.dirs(path = callranger_result_dir, full.names = FALSE, recursive = FALSE)
  sample_folders <- sample_folders[-grep("aggr", sample_folders)]
  
  ### load metric files into R memory space
  metric_info <- vector("list", length = length(sample_folders))
  names(metric_info) <- sample_folders
  metric_info2 <- NULL
  for(sp in names(metric_info)) {
    writeLines(paste(sp))
    metric_info[[sp]] <- t(read.csv(file = paste0(callranger_result_dir, sp, "/outs/metrics_summary.csv"),
                                    stringsAsFactors = FALSE, check.names = FALSE))
    if(is.null(metric_info2)) {
      metric_info2 <- metric_info[[sp]]
      colnames(metric_info2)[1] <- sp
    } else {
      metric_info2 <- merge(metric_info2, metric_info[[sp]], by = 0, all = TRUE)
      rownames(metric_info2) <- metric_info2[,1]
      metric_info2 <- metric_info2[,-1]
      colnames(metric_info2)[ncol(metric_info2)] <- sp
    }
  }
  
  ### draw bar graphs with some features
  plot_df <- data.frame(Sample=colnames(metric_info2),
                        Number_of_Reads=as.numeric(gsub(",", "", metric_info2["Number of Reads",])),
                        Number_of_Cells=as.numeric(gsub(",", "", metric_info2["Estimated Number of Cells",])),
                        Mean_Reads_per_Cell=as.numeric(gsub(",", "", metric_info2["Mean Reads per Cell",])),
                        Median_Genes_per_Cell=as.numeric(gsub(",", "", metric_info2["Median Genes per Cell",])),
                        Median_UMI_Counts_per_Cell=as.numeric(gsub(",", "", metric_info2["Median UMI Counts per Cell",])),
                        Total_Genes_Detected=as.numeric(gsub(",", "", metric_info2["Total Genes Detected",])),
                        stringsAsFactors = FALSE, check.names = FALSE)
  
  p <- vector("list", length = ncol(plot_df)-1)
  names(p) <- colnames(plot_df)[-1]
  
  for(col in names(p)) {
    p[[col]] <- ggplot(data=plot_df, aes_string(x="Sample", y=col, label=col)) +
      geom_bar(stat = "identity", fill = "gray60") +
      ggtitle("") +
      geom_text(hjust=0.6, color="black", size=3) +
      coord_flip() +
      theme_classic(base_size = 30) +
      theme(plot.title = element_text(hjust = 0.5, vjust = 0.5, size = 30),
            axis.title = element_text(hjust = 0.5, vjust = 0.5, size = 24),
            axis.text.x = element_text(hjust = 0.5, vjust = 0.5, size = 16),
            axis.ticks = element_blank())
  }
  
  g <- arrangeGrob(grobs = p,
                   nrow = 3,
                   ncol = 2)
  ggsave(file = paste0("./Wenjun_Data_QC_Results.pdf"), g, width = 25, height = 18)
  
  
  ### load the aggregated Wenjun dataset generated by cellranger aggr
  wenjun.data <- Read10X(data.dir = aggr_feature_bc_mat_dir)
  
  ### create a Seurat object
  ### min.cells : include genes detected in at least this many cells
  ### min.features : include cells where at least this many features are detected
  Wenjun_Seurat_Obj <- CreateSeuratObject(counts = wenjun.data,
                                          project = "Wenjun_HSPC",
                                          min.cells = 3,
                                          min.features = 200)
  
  ### MT percentage
  Wenjun_Seurat_Obj[["percent.mt"]] <- PercentageFeatureSet(Wenjun_Seurat_Obj, pattern = "^MT-")
  
  ### Visualize QC metrics as a violin plot
  VlnPlot(Wenjun_Seurat_Obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
  plot(density(Wenjun_Seurat_Obj@meta.data$nFeature_RNA))
  plot(density(Wenjun_Seurat_Obj@meta.data$percent.mt))
  
  ### Filter cells that have unique feature counts over 5000 or less than 300
  ### Filter cells that have > 10% mitochondrial counts
  Wenjun_Seurat_Obj <- subset(Wenjun_Seurat_Obj, subset = nFeature_RNA > 300 & nFeature_RNA < 5000 & percent.mt < 10)
  
  ### normalization
  Wenjun_Seurat_Obj <- NormalizeData(Wenjun_Seurat_Obj,
                                     normalization.method = "LogNormalize", scale.factor = 10000)
  
  ### Cell cycle score (will be used later for regression out)
  Wenjun_Seurat_Obj <- CellCycleScoring(object = Wenjun_Seurat_Obj,
                                        g2m.features = cc.genes$g2m.genes,
                                        s.features = cc.genes$s.genes)
  
  ### find variable genes
  Wenjun_Seurat_Obj <- FindVariableFeatures(Wenjun_Seurat_Obj,
                                            selection.method = "vst", nfeatures = 2000)
  
  ### scaling
  Wenjun_Seurat_Obj <- ScaleData(Wenjun_Seurat_Obj,
                                 vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"))
  
  ### PCA
  Wenjun_Seurat_Obj <- RunPCA(Wenjun_Seurat_Obj,
                              features = VariableFeatures(object = Wenjun_Seurat_Obj), npcs)
  
  ### UMAP
  Wenjun_Seurat_Obj <- RunUMAP(Wenjun_Seurat_Obj, dims = 1:15)
  
  ### clustering
  Wenjun_Seurat_Obj <- FindNeighbors(Wenjun_Seurat_Obj, dims = 1:10)
  Wenjun_Seurat_Obj <- FindClusters(Wenjun_Seurat_Obj, resolution = 0.5)
  
  ### save the Seurat object as RDS file
  saveRDS(Wenjun_Seurat_Obj, file = output_obj_path)
  
  ### draw a UMAP
  p <- DimPlot(object = Wenjun_Seurat_Obj, reduction = "umap", raster = TRUE,
               group.by = "",
               pt.size = 1) +
    ggtitle(paste0("")) +
    labs(color = "") +
    guides(colour = guide_legend(override.aes = list(size=10))) +
    theme_classic(base_size = 48) +
    theme(plot.title = element_text(hjust = 0.5, vjust = 0.5, size = 36, color = "black", face = "bold"),
          axis.title = element_text(size = 36, color = "black", face = "bold"),
          axis.text = element_text(size = 36, color = "black", face = "bold"),
          legend.title = element_text(size = 24, color = "black", face = "bold"),
          legend.text = element_text(size = 24, color = "black", face = "bold"),
          axis.ticks = element_blank())
  ggsave(paste0("./Wenjun_UMAP_Clusters.png"), plot = p, width = 20, height = 10, dpi = 350)
  
  
  
}